services:
  four-oh-four:
    build: .
    image: ghcr.io/williamjacksn/four-oh-four
    init: true
    environment:
      DB: postgres://postgres:postgres@postgres/postgres

  pip-compile:
    entrypoint:
      - /home/python/venv/bin/pip-compile
    image: ghcr.io/williamjacksn/pip-tools:py3.12
    init: true
    volumes:
      - ./:/home/python/four-oh-four
    working_dir: /home/python/four-oh-four

  postgres:
    image: postgres:11
    environment:
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data/11
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
