version: '3.8'

services:
  four-oh-four:
    build: .
    image: ghcr.io/williamjacksn/four-oh-four
    init: true
    environment:
      DB: postgres://postgres:postgres@postgres/postgres

  postgres:
    image: postgres:11.7-alpine
    environment:
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data/11
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
